import type { Restaurant } from "./types";

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "1",
    name: "맛있는 한식당",
    category: "한식",
    distanceText: "350m",
    priceLevel: "₩₩",
    rating: 4.5,
    isOpen: true,
    menuItems: ["김치찌개", "된장찌개", "비빔밥", "불고기"],
    isBookmarked: false,
  },
  {
    id: "2",
    name: "중화요리 전문점",
    category: "중식",
    distanceText: "520m",
    priceLevel: "₩₩₩",
    rating: 4.3,
    isOpen: true,
    menuItems: ["짜장면", "짬뽕", "탕수육", "양장피"],
    isBookmarked: false,
  },
  {
    id: "3",
    name: "스시 바",
    category: "일식",
    distanceText: "780m",
    priceLevel: "₩₩₩₩",
    rating: 4.8,
    isOpen: false,
    menuItems: ["초밥", "회", "우동", "돈카츠"],
    isBookmarked: false,
  },
  {
    id: "4",
    name: "파스타 하우스",
    category: "양식",
    distanceText: "420m",
    priceLevel: "₩₩₩",
    rating: 4.2,
    isOpen: true,
    menuItems: ["파스타", "스테이크", "리조또", "샐러드"],
    isBookmarked: false,
  },
  {
    id: "5",
    name: "떡볶이 천국",
    category: "분식",
    distanceText: "180m",
    priceLevel: "₩",
    rating: 4.6,
    isOpen: true,
    menuItems: ["떡볶이", "순대", "튀김", "김밥"],
    isBookmarked: false,
  },
  {
    id: "6",
    name: "달콤 카페",
    category: "카페/디저트",
    distanceText: "290m",
    priceLevel: "₩₩",
    rating: 4.4,
    isOpen: true,
    menuItems: ["커피", "케이크", "마카롱", "빙수"],
    isBookmarked: false,
  },
  {
    id: "7",
    name: "치킨 마스터",
    category: "치킨",
    distanceText: "640m",
    priceLevel: "₩₩",
    rating: 4.7,
    isOpen: true,
    menuItems: ["치킨", "양념치킨", "후라이드치킨"],
    isBookmarked: false,
  },
  {
    id: "8",
    name: "피자 플래닛",
    category: "피자",
    distanceText: "450m",
    priceLevel: "₩₩₩",
    rating: 4.1,
    isOpen: true,
    menuItems: ["피자", "파스타", "샐러드"],
    isBookmarked: false,
  },
  {
    id: "9",
    name: "버거킹덤",
    category: "버거",
    distanceText: "330m",
    priceLevel: "₩₩",
    rating: 4.3,
    isOpen: true,
    menuItems: ["햄버거", "감자튀김", "치킨너겟"],
    isBookmarked: false,
  },
  {
    id: "10",
    name: "쌀국수 하우스",
    category: "베트남/태국",
    distanceText: "570m",
    priceLevel: "₩₩",
    rating: 4.6,
    isOpen: false,
    menuItems: ["쌀국수", "분짜", "반미", "월남쌈"],
    isBookmarked: false,
  },
  {
    id: "11",
    name: "인도 커리",
    category: "인도/네팔",
    distanceText: "820m",
    priceLevel: "₩₩",
    rating: 4.4,
    isOpen: true,
    menuItems: ["인도 커리", "난", "탄두리 치킨", "비리야니"],
    isBookmarked: false,
  },
  {
    id: "12",
    name: "타코 벨",
    category: "멕시칸",
    distanceText: "720m",
    priceLevel: "₩₩₩",
    rating: 4.2,
    isOpen: true,
    menuItems: ["타코", "부리또", "케밥"],
    isBookmarked: false,
  },
  {
    id: "13",
    name: "라면 천국",
    category: "한식",
    distanceText: "410m",
    priceLevel: "₩",
    rating: 4.0,
    isOpen: true,
    menuItems: ["라면", "김밥", "떡볶이"],
    isBookmarked: false,
  },
  {
    id: "14",
    name: "삼겹살 명가",
    category: "한식",
    distanceText: "630m",
    priceLevel: "₩₩₩",
    rating: 4.9,
    isOpen: true,
    menuItems: ["삼겹살", "갈비", "냉면", "된장찌개"],
    isBookmarked: false,
  },
  {
    id: "15",
    name: "마라탕 천국",
    category: "중식",
    distanceText: "380m",
    priceLevel: "₩₩",
    rating: 4.5,
    isOpen: true,
    menuItems: ["마라탕", "마라샹궈", "깐풍기"],
    isBookmarked: false,
  },
  {
    id: "16",
    name: "라멘집",
    category: "일식",
    distanceText: "550m",
    priceLevel: "₩₩",
    rating: 4.6,
    isOpen: true,
    menuItems: ["라멘", "돈카츠", "규동", "카레"],
    isBookmarked: false,
  },
  {
    id: "17",
    name: "냉면 명가",
    category: "한식",
    distanceText: "470m",
    priceLevel: "₩₩",
    rating: 4.7,
    isOpen: true,
    menuItems: ["냉면", "막국수", "칼국수", "만두"],
    isBookmarked: false,
  },
  {
    id: "18",
    name: "족발 보쌈",
    category: "한식",
    distanceText: "690m",
    priceLevel: "₩₩₩",
    rating: 4.4,
    isOpen: true,
    menuItems: ["족발", "보쌈", "쌈밥"],
    isBookmarked: false,
  },
  {
    id: "19",
    name: "찜닭 골목",
    category: "한식",
    distanceText: "510m",
    priceLevel: "₩₩",
    rating: 4.3,
    isOpen: true,
    menuItems: ["찜닭", "닭갈비"],
    isBookmarked: false,
  },
  {
    id: "20",
    name: "똠얌꿍",
    category: "베트남/태국",
    distanceText: "840m",
    priceLevel: "₩₩",
    rating: 4.5,
    isOpen: true,
    menuItems: ["똠얌꿍", "팟타이", "카오팟"],
    isBookmarked: false,
  },
];

